### ISSUE TITLE
Check if we need to have http-server installed globally, and update readme if so

### ISSUE THREAD

**Issue by gmaliandi** [UnboundVR/metavrse-client#55]

**Comment by tmilar** [comment]
Hi @gmaliandi , I just installed and ran the whole project in my local machine succesfully without having installed an http-server global dependency. 

Branch 'dev' for both metavrse-server and metavrse-client. Windows 8.1, node v5.11.0, npm v3.8.6

Also, created PR #73 for an improvement in README instructions

**Comment by gmaliandi** [comment]
Awesome then, we can close it!
